### ISSUE TITLE
Construct endpoint in the plugin

### ISSUE THREAD

**Issue by xpdable** [DataDog/kong-plugin-ddtrace#19]
Similar with #15 , we are deploying kong with helm into EKS and the endpoint is dynamic.
With the same usage of datadog-kong-plugin (https://docs.konghq.com/hub/kong-inc/datadog/), we fetch the ip and config the plugin as below:
```yaml
env:
  KONG_DATADOG_AGENT_HOST:
    valueFrom:
      fieldRef:
        fieldPath: status.hostIP
...
dblessConfig:
  config:
    _format_version: "2.1"
    plugins:
      - name: datadog
        config:
          host: "{vault://env/KONG_DATADOG_AGENT_HOST}"
          port: 8125
      - name: ddtrace
        config:
          service_name: kong-ddtrace
          agent_endpoint: "http://{vault://env/KONG_DATADOG_AGENT_HOST}:8126/v0.4/traces"
          environment: 'dev'
```

The datadog plugin works in this way. however the ddtrace plugin does not work. Please refer the error below:
```
2023/12/01 10:28:02 [error] 1277#0: *130 [kong] handler.lua:27 agent_writer error failed to request: [cosocket] DNS resolution failed: dns server error: 3 name error. Tried: ["(short)"{vault:(na) - cache-miss",""{vault.rdsdemo.svc.cluster.local:33 - cache-miss/querying/dns server error: 3 name error",""{vault.svc.cluster.local:33 - cache-miss/querying/dns server error: 3 name error",""{vault.cluster.local:33 - cache-miss/querying/dns server error: 3 name error",""{vault.eu-central-1.compute.internal:33 - cache-miss/querying/dns server error: 3 name error",""{vault:33 - cache-miss/querying/dns server error: 3 name error",""{vault.rdsdemo.svc.cluster.local:1 - cache-miss/querying/dns server error: 3 name error",""{vault.svc.cluster.local:1 - cache-miss/querying/dns server error: 3 name error",""{vault.cluster.local:1 - cache-miss/querying/dns server error: 3 name error",""{vault.eu-central-1.compute.internal:1 - cache-miss/querying/dns server error: 3 name error",""{vault:1 - cache-miss/querying/dns server error: 3 name error",""{vault.rdsdemo.svc.cluster.local:5 - cache-miss/querying/dns server error: 3 name error",""{vault.svc.cluster.local:5 - cache-miss/querying/dns server error: 3 name error",""{vault.cluster.local:5 - cache-miss/querying/dns server error: 3 name error",""{vault.eu-central-1.compute.internal:5 - cache-miss/querying/dns server error: 3 name error",""{vault:5 - cache-miss/querying/dns server error: 3 name error"], context: ngx.timer
```

Can you give some insight? Can ddtrace deal with it in the same way of datadog? Thanks

for example: ( split each part and construct endpoint in the plugin? ) 
```yaml
      - name: ddtrace
        config:
          service_name: kong-ddtrace
          host: "{vault://env/KONG_DATADOG_AGENT_HOST}"
          port: :8126
          version: "v4"
          environment: 'dev'
```
Also workable that if endpoint parameter exists, drop all others i.e. host, port...
