### ISSUE TITLE
Having issues installing the plugin in a k8s env

### ISSUE THREAD

**Issue by Manan-Kothari** [DataDog/kong-plugin-ddtrace#29]
Hi, we are using a custom forked version of kong where we build our own kong image and when installing the ddtrace plugin in the dockerfile and then enabling it, getting this error 

```
2024/01/24 18:09:08 [error] 1#0: init_by_lua error: /usr/local/share/lua/5.1/kong/init.lua:621: error loading plugin schemas: on plugin 'ddtrace': ddtrace plugin is enabled but not installed;
no plugin found
stack traceback:
	[C]: in function 'assert'
	/usr/local/share/lua/5.1/kong/init.lua:621: in function 'init'
	init_by_lua:3: in main chunk
nginx: [error] init_by_lua error: /usr/local/share/lua/5.1/kong/init.lua:621: error loading plugin schemas: on plugin 'ddtrace': ddtrace plugin is enabled but not installed;
no plugin found
stack traceback:
	[C]: in function 'assert'
	/usr/local/share/lua/5.1/kong/init.lua:621: in function 'init'
	init_by_lua:3: in main chunk
```

Our dockerfile looks like this 

<details>
  <summary>dockerfile</summary>
```
FROM kong:3.3.0-ubuntu
USER root

ARG POETRY_HTTP_BASIC_P44_USERNAME
ARG POETRY_HTTP_BASIC_P44_PASSWORD

ENV POETRY_HTTP_BASIC_P44_USERNAME=${POETRY_HTTP_BASIC_P44_USERNAME} \
    POETRY_HTTP_BASIC_P44_PASSWORD=${POETRY_HTTP_BASIC_P44_PASSWORD} \
    PYTHONUNBUFFERED=1 \
    PYTHONDONTWRITEBYTECODE=1 \
    PIP_DISABLE_PIP_VERSION_CHECK=1 \
    PIP_DEFAULT_TIMEOUT=100 \
    POETRY_NO_INTERACTION=1 \
    POETRY_VIRTUALENVS_IN_PROJECT=true

# Make sure home directory exists
RUN mkdir -p /home/kong

# Install system deps
RUN apt-get update \
&& apt-get -y install python3-pip musl-dev libffi-dev gcc g++ file make librdkafka1 librdkafka-dev \
&& apt-get clean \
&& pip3 install --upgrade pip setuptools poetry==1.4.1

# Install Python dependencies
COPY ./pyproject.toml ./poetry.lock /home/kong/
RUN cd /home/kong  \
&& poetry export --without dev --with-credentials --no-ansi --without-hashes --format=requirements.txt > requirements.txt  \
&& pip3 install -r requirements.txt  \
&& rm pyproject.toml poetry.lock requirements.txt
# Install dd-trace-plugin
RUN luarocks install kong-plugin-ddtrace
# Copy Kong plugins
COPY ./custom_plugins/py /home/kong/plugins
COPY ./bin /home/kong/bin
RUN chmod -R 775 /home/kong/plugins /home/kong/bin

RUN chown -R kong:kong /home/kong

# Temporary patch for https://github.com/Kong/kong-python-pdk/issues/120
COPY ./patches/kong_pdk/server.patch /usr/local/lib/python3.10/dist-packages/kong_pdk/
RUN patch /usr/local/lib/python3.10/dist-packages/kong_pdk/server.py < /usr/local/lib/python3.10/dist-packages/kong_pdk/server.patch

# Temporary patch for https://github.com/Kong/kong/issues/11173
COPY ./patches/kong/runloop/handler.patch /usr/local/share/lua/5.1/kong/runloop/
RUN patch /usr/local/share/lua/5.1/kong/runloop/handler.lua < /usr/local/share/lua/5.1/kong/runloop/handler.patch

# Initialize Kong
USER kong
ENTRYPOINT ["/home/kong/bin/docker-entrypoint.sh"]
EXPOSE 8000 8443 8001 8444
STOPSIGNAL SIGQUIT
HEALTHCHECK --interval=10s --timeout=10s --retries=10 CMD kong health
CMD ["kong", "docker-start"]
```
</details>

and then in our helm chart we have the following 

```yaml
env:
    # All custom plugin names must be present here
    PLUGINS: "bundled,request_to_shared_context,auth_session_to_headers,cookie_token_to_header,sleuth_trace_header_injector,statsd,cors_filter,rate_limit,rate_limit_for_tenant,xss_filter,api_logger,disable_auth,request_terminator,request_sanitizer,propagate_query_parameters,access_group_allowlist_filter,metrics_reporter,ddtrace"
    LOG_LEVEL: "debug"
  dblessConfig:
    config:
      _format_version: "2.23.0"
      plugins:
        - name: ddtrace
          config:
            service_name: p44-kong
            agent_host: "{vault://env/dd-agent-host}"
            environment: 'qa-integration'
```

we are setting the env variables as well for the host, etc but it looks it can't even find the plugin

When we run this locally and check if the plugin is available in the kong config, we do see it (using that same dockerfile)
 
[p44-kong-config.json](https://github.com/DataDog/kong-plugin-ddtrace/files/14042495/p44-kong-config.json)
