### ISSUE TITLE
[Bug]: `kong.log.warning` Function Call Results in `nil` Error

### ISSUE THREAD

**Issue by tmizohata-alist** [DataDog/kong-plugin-ddtrace#48]
### Kong Version

3.3.1

### Plugin Version

0.2.0

### On which environment your Kong instance is running?

Kubernetes

### Plugin Configuration

```yaml
config:
  service_name: api-gateway
  agent_endpoint:
  trace_agent_port:
  header_tags:
  static_tags:
  injection_propagation_styles:
  - datadog
  - tracecontext
  extraction_propagation_styles:
  - datadog
  - tracecontext
  initial_samples_per_second: 100
  version:
  max_header_size: 512
  resource_name_rule:
  generate_128bit_trace_ids: true
  environment:
  trace_agent_url: http://ddagent:8126
  initial_sample_rate:
  agent_host:
```

### What happened?

I have recently started using the `ddtrace` plugin. While the plugin appears to function correctly in terms of features, numerous error messages are generated in the logs.

**Error Log:**
```
[kong] handler.lua:360 
[ddtrace] tracing error in DatadogTraceHandler:header_filter: /usr/local/share/lua/5.1/kong/plugins/ddtrace/w3c_propagation.lua:104:
  attempt to call field 'warning' (a nil value) while reading response header from upstream
```

By looking at [the code](https://github.com/DataDog/kong-plugin-ddtrace/blob/cd89c06d63c1c7255d66873f5d89a6735bb06548/kong/plugins/ddtrace/w3c_propagation.lua#L101-L106)

```lua
if tracestate then
    dd_state, err = parse_datadog_tracestate(tracestate)
    if err then
        kong.log.warning(err)
    end
end
```

`kong.log` seems to be `nil` on some occasions. Is this a bug? Or you think some configurations can fix this?
