### ISSUE TITLE
[Bug]: Breaking change between 0.1 and 0.2 because of deprecated config

### ISSUE THREAD

**Issue by lays147** [DataDog/kong-plugin-ddtrace#52]
### Kong Version

3.6.1

### Plugin Version

0.2.0-1

### On which environment your Kong instance is running?

Docker

### Plugin Configuration

```yaml
_format_version: "3.0"

_info:
  defaults: {}
  select_tags:
    - ddtrace

plugins:
  - name: ddtrace
    tags:
      - ddtrace
    config:
      environment: prd
```

### What happened?

The deprecation of the field `agent_endpoint` causes a breaking change that causes Kong to fail when the latest version of this plugin is added to the docker image. 

Since the plugin is configured based on the 0.1.2 version, if I deploy the latest version, Kong fails to read the plugins configuration from the Control Plane, so the Data Plane doesn't load all the configuration for services and gateways. 

The Control Plane isn't accessible outside my infrastructure, and I can't access it, so I'm unable to fix the configuration or disable this plugin for further fixing. 

```
 [error] 1361#0: *7 [lua] data_plane.lua:263: [clustering] unable to update running config: bad config received from control plane in 'plugins':
  - in entry 3 of 'plugins':
  in 'config':
  in 'agent_endpoint': agent_endpoint is deprecated. Please use trace_agent_url or agent_host instead, context: ngx.timer
```

This plugin should handle the breaking change gracefully without impacting Kong start.
