### ISSUE TITLE
[Bug]: Warning logs on environment read in latest version

### ISSUE THREAD

**Issue by lays147** [DataDog/kong-plugin-ddtrace#53]
### Kong Version

3.6.1

### Plugin Version

0.2.0-1

### On which environment your Kong instance is running?

ECS

### Plugin Configuration

```yaml
_format_version: "3.0"

_info:
  defaults: {}
  select_tags:
    - ddtrace

plugins:
  - name: ddtrace
    tags:
      - ddtrace
    config:
      service_name: my-api-gateway
      environment: production
      static_tags:
        - name: app
          value: my-api-gateway
```

### What happened?

Within this latest version, I'm getting several warning logs from the plugin about errors on reading the env configs from a vault: 
![image](https://github.com/DataDog/kong-plugin-ddtrace/assets/7799231/73a7e196-3087-4c15-bc75-4e4a695bab68)

```
2024/04/16 16:33:48 [warn] 1363#0: *2487 [kong] vault.lua:1255 could not retrieve value for reference {vault://env/DD_TRACE_PROPAGATION_STYLE_EXTRACT} (could not get value from external vault (no value found)), context: ngx.timer
``` 
I don't even have a vault configured within this Kong.

This is not impacting the availability of the Kong Gateway, but it's a very verbose log that's being triggered all the time.
