### ISSUE TITLE
[Question]: Doubts about the trace generated by this plugin

### ISSUE THREAD

**Issue by lays147** [DataDog/kong-plugin-ddtrace#54]
### Kong Version

3.6.1

### Plugin Version

0.2.0-1

### On which environment your Kong instance is running?

Other

### Plugin Configuration

```yaml
_format_version: "3.0"

_info:
  defaults: {}
  select_tags:
    - ddtrace

plugins:
  - name: ddtrace
    tags:
      - ddtrace
    config:
      service_name: my-api-gateway
      environment: production
      version: v0.1.1
      static_tags:
        - name: app
          value: my-api-gateway
```

### What happened?

I'm new to using traces in Datadog, so here is a question:

With the plugin enabled, the traces are not being correlated with the kong access log. The upstream server logs shows the traces as from this service, but the logs of the service itself does not contain any trace. 

The kong access log uses a custom nginx format, and I don't know if this impacts the datadog tracing.

Is there something that I'm missing?
