### ISSUE TITLE
[Bug]: DatadogTraceHandler Attempt to Call Extractor Failed

### ISSUE THREAD

**Issue by mfischler** [DataDog/kong-plugin-ddtrace#57]
### Kong Version

3.6.1

### Plugin Version

0.2.0-1

### On which environment your Kong instance is running?

Kubernetes

### Plugin Configuration

```yaml
- name: ddtrace
    config:
      service_name: SERVICE_NAME
      injection_propagation_styles:
        - datadog
      extraction_propagation_styles:
        - datadog
      header_tags:
        - header: X-Gateway
          tag: gateway
      resource_name_rule:
        - match: /route/\w*/info
          replacement: /route/?/info


DD_ENV:
  valueFrom:
    fieldRef:
      fieldPath: metadata.labels['tags.datadoghq.com/env']
DD_SERVICE:
  valueFrom:
    fieldRef:
      fieldPath: metadata.labels['tags.datadoghq.com/service']
DD_VERSION:
  valueFrom:
    fieldRef:
      fieldPath: metadata.labels['tags.datadoghq.com/version']
DD_AGENT_HOST:
  valueFrom:
    fieldRef:
      fieldPath: status.hostIP
DD_TRACE_AGENT_PORT: 8126
DD_TRACE_AGENT_URL: http://$(DATADOG_AGENT_HOST):$(DATADOG_TRACE_AGENT_PORT)
DD_TRACE_PROPAGATION_STYLE_INJECT: '["datadog"]'
DD_TRACE_PROPAGATION_STYLE_EXTRACT: '["datadog"]'
```

### What happened?

[error] 1322#0: *2498 [kong] handler.lua:360 [ddtrace] tracing error in DatadogTraceHandler:header_filter: ...local/share/lua/5.1/kong/plugins/ddtrace/propagation.lua:41: attempt to call local 'extractor' (a nil value) while reading response header from upstream, client: 192.168.x.x

[error] 1322#0: *2498 [kong] handler.lua:379 [ddtrace] tracing error in DatadogTraceHandler:body_filter: ...local/share/lua/5.1/kong/plugins/ddtrace/propagation.lua:41: attempt to call local 'extractor' (a nil value) while sending to client, client: 192.168.x.x

[error] 1322#0: *2498 [kong] handler.lua:379 [ddtrace] tracing error in DatadogTraceHandler:body_filter: ...local/share/lua/5.1/kong/plugins/ddtrace/propagation.lua:41: attempt to call local 'extractor' (a nil value) while sending to client, client: 192.168.x.x

Type: Kong DB-Less
Kubernetes: 1.28

I suspect that DDTrace Plugin does not have access due to permissions. Would 'kong.ctx.shared' work instead?
