### ISSUE TITLE
[Bug]:  unable to enable ddtrace plugin 

### ISSUE THREAD

**Issue by vibhavachar** [DataDog/kong-plugin-ddtrace#62]
### Kong Version

/usr/local/share/lua/5.1/kong/plugins/ddtrace $ kong version 2.0.0

### Plugin Version

/usr/local/share/lua/5.1/kong/plugins/ddtrace $ luarocks list kong-plugin-ddtrace  Rocks installed for Lua 5.1 ---------------------------  kong-plugin-ddtrace    0.2.0-1 (installed) - /usr/local/lib/luarocks/rocks-5.1

### On which environment your Kong instance is running?

Kubernetes

### Plugin Configuration

```yaml
curl -i -X POST --url http://localhost:8005/plugins/ --data 'name=ddtrace'
HTTP/1.1 400 Bad Request
Date: Wed, 29 May 2024 07:12:58 GMT
Content-Type: application/json; charset=utf-8
Connection: keep-alive
Access-Control-Allow-Origin: *
Server: kong/2.0.0
Content-Length: 247
X-Kong-Admin-Latency: 1

{"message":"schema violation (name: plugin 'ddtrace' not enabled; add it to the 'plugins' configuration property)","name":"schema violation","fields":{"name":"plugin 'ddtrace' not enabled; add it to the 'plugins' configuration property"},
```

### What happened?

A bug happened!
