### ISSUE TITLE
[Bug]: Plugin stopped working with Kong version 3.7.1

### ISSUE THREAD

**Issue by NHMPB** [DataDog/kong-plugin-ddtrace#69]
### Kong Version

3.7.1

### Plugin Version

0.2.1

### On which environment your Kong instance is running?

Kubernetes

### Plugin Configuration

```json
"plugins": [
    {
        "name": "ddtrace",
        "config": {
             "service_name": "kong",
             "environment": "uat"
             "version": "v1.0.0"
        }
    }
],
```

### What happened?

After updating Kong to 3.7.1, the plugin stopped working and Kong is not listed anymore in APM. In the logs in Datadog, the following error is logged for each request:

`[error] 1334#0: *55588 [kong] handler.lua:28 agent_writer error failed to request: connection refused, context: ngx.timer`

**Comment by dmehala** [comment]
Hi @NHMPB 

Thank you for flagging this issue. I'll take a look tomorrow and keep you posted.

**Comment by dmehala** [comment]
Hi @NHMPB 

Are you using environment variables to configure the plugin?

**Comment by NHMPB** [comment]
Hi @dmehala,
The only config for the ddtrace plugin specifically we have is the one which I posted in my initial message. Additionally, we have the following environment variables set for all our pods (kong and also other services) according to Datadog documentation:

- `DD_AGENT_HOST`: `(v1:status.hostIP)`
- `DD_ENV`: same value as above
- `DD_SERVICE`: same value as above
- `DD_VERSION`: same value as above

Is that what you mean?

**Comment by dmehala** [comment]
Yep, that's what I mean. Thanks.

It appears that in recent versions of Kong, environment variables are no longer being read correctly. As a result, `DD_AGENT_HOST` cannot be resolved, and the plugin is unable to determine how to reach the agent. As a workaround, I recommend adding the `agent_host` parameter directly to your plugin configuration. Your configuration should look like this

```yaml
"plugins": [
    {
        "name": "ddtrace",
        "config": {
             "agent_host": "<MY_DATADOG_HOST_AGENT>",
             "service_name": "kong",
             "environment": "uat"
             "version": "v1.0.0"
        }
    }
],
```

Let me know it fix your issue.
