### ISSUE TITLE
[Bug]: Getting agent_writer error in Datadog after kong upgrade to 3.7.1

### ISSUE THREAD

**Issue by withgokul** [DataDog/kong-plugin-ddtrace#71]
### Kong Version

3.7.1

### Plugin Version

 0.2.0-1 (installed) - /usr/local/lib/luarocks/rocks-5.1

### On which environment your Kong instance is running?

Kubernetes

### Plugin Configuration

```yaml
dblessConfig:
    # Either Kong's configuration is managed from an existing ConfigMap (with Key: kong.yml)
    # configMap: "kong-config"
    config:
      plugins:
        - name: prometheus
          config:
            per_consumer: true
            status_code_metrics: true
            latency_metrics: true
            bandwidth_metrics: true
            upstream_health_metrics: true
        - name: datadog
          config:
            host: "{vault://env-vault/KONG_DATADOG_AGENT_HOST}"
            service_name_tag: oneapi-nafta
            port: 8125
        - name: ddtrace
          config:
            service_name: oneapi-nafta
            header_tags:
             - header: X-Oneapi-Gateway
               tag: oneapi-gateway
            injection_propagation_styles:
             - datadog
            extraction_propagation_styles:
             - datadog
```

### What happened?

Hello, After the kong upgrade from 3.6.1 to 3.7.1, we are seeing the below error continuously in datadog.
Could you please help to fix this issue?

I saw the other thread on this topic "https://github.com/DataDog/kong-plugin-ddtrace/issues/69", but i was not able to understand the fix provided and how it can be applied in my case.

The above snippet is from the helm values files we used.
We tried to update the local config file for one of the gateway with below entry but we still have the error:

OPTION 1
    config:
      plugins:
        - name: ddtrace
          config:
            service_name: oneapi-nafta
            #agent_host: 192.168.109.253
            agent_host: "{vault://env-vault/KONG_DATADOG_AGENT_HOST}"

OPTION 2:
    config:
      plugins:
        - name: ddtrace
          config:
            service_name: oneapi-nafta
            #agent_host: 192.168.109.253
            agent_host: datadog-agent

We still have the error.
Kindly help.

**Comment by withgokul** [comment]
Error in Datadog:

2025/02/12 10:39:07 [error] 1334#0: *3850 [kong] handler.lua:27 agent_writer error failed to request: bad uri: /v0.4/traces, context: ngx.timer

**Comment by dmehala** [comment]
Add the `agent_host` to `ddtrace` configuration. The following should do the job: 
```
dblessConfig:
    # Either Kong's configuration is managed from an existing ConfigMap (with Key: kong.yml)
    # configMap: "kong-config"
    config:
      plugins:
        ...
        - name: ddtrace
          config:
            service_name: oneapi-nafta
            agent_host: "{vault://env-vault/KONG_DATADOG_AGENT_HOST}"
            header_tags:
             - header: X-Oneapi-Gateway
               tag: oneapi-gateway
            injection_propagation_styles:
             - datadog
            extraction_propagation_styles:
             - datadog
           ```
