### ISSUE TITLE
[Bug]: Many Log Lines in Error Logs for DATADOG TRACER CONFIGURATION

### ISSUE THREAD

**Issue by corteva-ryanbonham** [DataDog/kong-plugin-ddtrace#77]
### Kong Version

3.6.1

### Plugin Version

0.2.2

### On which environment your Kong instance is running?

Other

### Plugin Configuration

```yaml
{
    "initial_sample_rate": null,
    "initial_samples_per_second": 100,
    "agent_endpoint": "http://localhost:8126/v0.4/traces",
    "static_tags": null,
    "service_name": "XXXX",
    "resource_name_rule": null,
    "environment": "XXXX"
  },
```

### What happened?

Large amounts of log's in error, which look like they should be DEEBUG()

```
2025/03/20 14:00:31 [info] 7439#0: *28047 [kong] handler.lua:220 [ddtrace] DATADOG TRACER CONFIGURATION - { ["extraction_propagation_styles"] = { [1] = datadog,[2] = tracecontext,} ,["injection_propagation_styles"] = { [1] = datadog,[2] = tracecontext,} ,["service"] = fields-svc,["agent_url"] = http://localhost:8126,["environment"] = XXX ,["__id__"] = 717,} , client: 10.255.249.239, server: kong, request: "GET /something HTTP/1.1", host: "us.example.com", request_id: "7e5a7448223e7b3533f50f1ffe967a38"
```
