### ISSUE TITLE
[Bug]: ddtrace plugin buffers reponse preventing a streaming response

### ISSUE THREAD

**Issue by bourlaad** [DataDog/kong-plugin-ddtrace#88]
### Kong Version

3.7.1

### Plugin Version

0.2.3

### On which environment your Kong instance is running?

Docker

### Plugin Configuration

```yaml
"config": {
        "agent_host": null,
        "trace_agent_port": null,
        "environment": "granapptest",
        "trace_agent_url": null,
        "injection_propagation_styles": [
          "datadog",
          "tracecontext"
        ],
        "extraction_propagation_styles": [
          "datadog",
          "tracecontext"
        ],
        "agent_endpoint": null,
        "startup_log": true,
        "initial_samples_per_second": 100,
        "initial_sample_rate": null,
        "max_header_size": 512,
        "static_tags": null,
        "service_name": "chatbot-svc",
        "generate_128bit_trace_ids": true,
        "header_tags": null,
        "resource_name_rule": null,
        "version": null
      }
```

### What happened?

The route hosts an endpoint that is supposed to return a content type of 'text/event-stream'. With the plugin removed, it properly streams out the response. When the plugin is added an configured, the response is returned, but not streaming. It appears that there is some sort of response buffer in the ddtrace plugin that waits for the whole response and returns it all at once
